# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(blank=True, default='', max_length=10)),
                ('record_time', models.FloatField(default=1488083912.0, max_length=20)),
                ('is_right', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('record_time',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromLang', models.CharField(max_length=5)),
                ('toLang', models.CharField(max_length=5)),
                ('definition', models.CharField(blank=True, default='', max_length=100)),
                ('phonetic', models.CharField(blank=True, default='', max_length=100)),
                ('word', models.CharField(blank=True, default='', max_length=100)),
                ('audio', models.CharField(blank=True, default='', max_length=100)),
                ('sentence', models.CharField(blank=True, default='', max_length=200)),
                ('trans', models.CharField(blank=True, default='', max_length=200)),
                ('is_known', models.IntegerField(default=0)),
                ('mark_time', models.FloatField(default=1488083912.0, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
        migrations.AddField(
            model_name='quesrecord',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iw.Word'),
        ),
    ]
